// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/documents": {
            "post": {
                "summary": "Create Document",
                "responses": {}
            }
        },
        "/documents/calendar": {
            "post": {
                "summary": "Get Calendar Documents",
                "responses": {}
            }
        },
        "/documents/update/{id}": {
            "patch": {
                "summary": "Update Document",
                "responses": {}
            }
        },
        "/documents/{id}": {
            "get": {
                "summary": "Get Document",
                "responses": {}
            },
            "delete": {
                "summary": "Delete Document",
                "responses": {}
            }
        },
        "/files/ai/{id}": {
            "get": {
                "summary": "Get File AI Analysis",
                "responses": {}
            }
        },
        "/files/ocr/{id}": {
            "get": {
                "summary": "Get File Text",
                "responses": {}
            }
        },
        "/files/upload": {
            "post": {
                "summary": "Upload File",
                "responses": {}
            }
        },
        "/files/{id}": {
            "get": {
                "summary": "Get File",
                "responses": {}
            },
            "delete": {
                "summary": "Delete File",
                "responses": {}
            }
        },
        "/user-details/ai-credits": {
            "get": {
                "summary": "Get AI Credit Usage",
                "responses": {}
            }
        },
        "/user-details/update": {
            "patch": {
                "summary": "Update User Profile",
                "responses": {}
            }
        },
        "/user-details/usage": {
            "get": {
                "summary": "Get User Usage",
                "responses": {}
            }
        },
        "/users/forgot-password": {
            "post": {
                "summary": "Forgot Password",
                "responses": {}
            }
        },
        "/users/google": {
            "post": {
                "summary": "Google Login",
                "responses": {}
            }
        },
        "/users/login": {
            "post": {
                "summary": "User Login",
                "responses": {}
            }
        },
        "/users/reset-password": {
            "post": {
                "summary": "Reset Password",
                "responses": {}
            }
        },
        "/users/signup": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "User Signup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date of Birth (YYYY-MM-DD)",
                        "name": "dob",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Gender",
                        "name": "gender",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Profile Picture",
                        "name": "profile_pic",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/verify-otp": {
            "post": {
                "summary": "Verify OTP",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Vita Track AI API",
	Description:      "API documentation for Vita Track AI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
