// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/documents": {
            "post": {
                "tags": [
                    "Document"
                ],
                "summary": "Create Document",
                "responses": {}
            }
        },
        "/documents/calendar": {
            "post": {
                "tags": [
                    "Document"
                ],
                "summary": "Get Calendar Documents",
                "responses": {}
            }
        },
        "/documents/update/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Document"
                ],
                "summary": "Update Document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category [Prescription or Medical Report]",
                        "name": "category",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "DocumentName",
                        "name": "document_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "DocumentDate (YYYY-MM-DD)",
                        "name": "document_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "tags",
                        "name": "Tags",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/documents/{id}": {
            "get": {
                "tags": [
                    "Document"
                ],
                "summary": "Get Document",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Document"
                ],
                "summary": "Delete Document",
                "responses": {}
            }
        },
        "/files/ai/{id}": {
            "get": {
                "tags": [
                    "File"
                ],
                "summary": "Get File AI Analysis",
                "responses": {}
            }
        },
        "/files/ocr/{id}": {
            "get": {
                "tags": [
                    "File"
                ],
                "summary": "Get File Text",
                "responses": {}
            }
        },
        "/files/upload": {
            "post": {
                "tags": [
                    "File"
                ],
                "summary": "Upload File",
                "responses": {}
            }
        },
        "/files/{id}": {
            "get": {
                "tags": [
                    "File"
                ],
                "summary": "Get File",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "File"
                ],
                "summary": "Delete File",
                "responses": {}
            }
        },
        "/health-metric/save": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new health metric entry for the logged-in user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Save health metric",
                "parameters": [
                    {
                        "description": "Health metric payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SaveHealthMetricRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "health metric saved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user-details/ai-credits": {
            "get": {
                "tags": [
                    "User-Details"
                ],
                "summary": "Get AI Credit Usage",
                "responses": {}
            }
        },
        "/user-details/update": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Details"
                ],
                "summary": "Update User Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "DeleteProfilePic",
                        "name": "delete_profile_pic",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Date of Birth (YYYY-MM-DD)",
                        "name": "dob",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Gender",
                        "name": "gender",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Profile Picture",
                        "name": "profile_pic",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user-details/usage": {
            "get": {
                "tags": [
                    "User-Details"
                ],
                "summary": "Get User Usage",
                "responses": {}
            }
        },
        "/users/forgot-password": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Forgot Password",
                "parameters": [
                    {
                        "description": "Forget Password payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ForgetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/google": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Google Login",
                "responses": {}
            }
        },
        "/users/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/reset-password": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Reset Password",
                "parameters": [
                    {
                        "description": "Reset Password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/signup": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User Signup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date of Birth (YYYY-MM-DD)",
                        "name": "dob",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Gender",
                        "name": "gender",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Profile Picture",
                        "name": "profile_pic",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/verify-otp": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Verify OTP",
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.ForgetPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.Measurement": {
            "type": "object",
            "properties": {
                "unit": {
                    "description": "e.g. \"kg\", \"lb\", \"mg/dL\", \"mmol/L\"",
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "models.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "email",
                "new_password",
                "otp"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                },
                "otp": {
                    "type": "string"
                }
            }
        },
        "models.SaveHealthMetricRequest": {
            "type": "object",
            "properties": {
                "blood_pressure": {
                    "type": "object",
                    "properties": {
                        "diastolic": {
                            "type": "integer",
                            "example": 80
                        },
                        "systolic": {
                            "type": "integer",
                            "example": 120
                        }
                    }
                },
                "blood_sugar": {
                    "$ref": "#/definitions/models.Measurement"
                },
                "calories": {
                    "description": "kcal burned/consumed",
                    "type": "integer",
                    "example": 2200
                },
                "heart_rate": {
                    "type": "integer",
                    "example": 72
                },
                "notes": {
                    "type": "string"
                },
                "oxygen_level": {
                    "description": "SpO2 (%)",
                    "type": "number",
                    "example": 98
                },
                "sleep_hours": {
                    "description": "hours (e.g., 7.5)",
                    "type": "number",
                    "example": 7.5
                },
                "steps": {
                    "description": "daily steps",
                    "type": "integer",
                    "example": 8500
                },
                "weight": {
                    "$ref": "#/definitions/models.Measurement"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Vita Track AI API",
	Description:      "API documentation for Vita Track AI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
