basePath: /api/v1
host: localhost:8081
info:
  contact: {}
  description: API documentation for Vita Track AI
  title: Vita Track AI API
  version: "1.0"
paths:
  /documents:
    post:
      responses: {}
      summary: Create Document
  /documents/{id}:
    delete:
      responses: {}
      summary: Delete Document
    get:
      responses: {}
      summary: Get Document
  /documents/calendar:
    post:
      responses: {}
      summary: Get Calendar Documents
  /documents/update/{id}:
    patch:
      responses: {}
      summary: Update Document
  /files/{id}:
    delete:
      responses: {}
      summary: Delete File
    get:
      responses: {}
      summary: Get File
  /files/ai/{id}:
    get:
      responses: {}
      summary: Get File AI Analysis
  /files/ocr/{id}:
    get:
      responses: {}
      summary: Get File Text
  /files/upload:
    post:
      responses: {}
      summary: Upload File
  /user-details/ai-credits:
    get:
      responses: {}
      summary: Get AI Credit Usage
  /user-details/update:
    patch:
      responses: {}
      summary: Update User Profile
  /user-details/usage:
    get:
      responses: {}
      summary: Get User Usage
  /users/forgot-password:
    post:
      responses: {}
      summary: Forgot Password
  /users/google:
    post:
      responses: {}
      summary: Google Login
  /users/login:
    post:
      responses: {}
      summary: User Login
  /users/reset-password:
    post:
      responses: {}
      summary: Reset Password
  /users/signup:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: Date of Birth (YYYY-MM-DD)
        in: formData
        name: dob
        type: string
      - description: Gender
        in: formData
        name: gender
        type: string
      - description: Profile Picture
        in: formData
        name: profile_pic
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: User Signup
  /users/verify-otp:
    post:
      responses: {}
      summary: Verify OTP
swagger: "2.0"
